### ISSUE TITLE
USB and internal Airport card

### ISSUE THREAD

**Issue by anthonyuk** [randyzhong/HP-EliteDesk-800-G2-DM-Hackintosh#1]
I think the internal Airport card is somehow linked to USB power as the wifi part works but not Bluetooth with your USB config.
I disabled the USBports.kext and it works fine.
A device BRCM20702 is detected on HS07 for me.

**Comment by ningye2012** [comment]
> I think the internal Airport card is somehow linked to USB power as the wifi part works but not Bluetooth with your USB config.
> I disabled the USBports.kext and it works fine.
> A device BRCM20702 is detected on HS07 for me.

me too,and cannot shutdown

**Comment by anthonyuk** [comment]
I re-did the USB config. My BT card is on HS07 and working now along with all others. 

Still have a wake from sleep issue though.

**Comment by randyzhong** [comment]
@anthonyuk @ningye2012 Thanks for providing updates.
Mine disabled built-in M2/BT so I may missed HS07. You can modify your USB Mapping file, remove USR1/2 and add HS07.

In terms of sleeping issue, HD 530 has a known sleep issue, a possible workaround is to disable HDMI audio by replacing the "hda-gfx" property with "**no-hda-gfx**" in your config.plist, but you will lost monitor audio.

**Comment by ningye2012** [comment]
@randyzhong Thanks for your share.

**Comment by ningye2012** [comment]
@randyzhong But again, I'm on another HP 600g2 DM（ CPU:6400T ）Using my original self configured oc0.6.2, the sleep is basically normal and there is no black screen phenomenon. It can wake up. Except for the Automatic wake-up after the nap is enabled, if you don't open the nap, you can basically wake up normally. This seems to indicate that it is not necessarily the problem of hd530.

**Comment by anthonyuk** [comment]
@randyzhong Thanks. That is exactly what I did to resolve the USB issue.
I use the no-hda-gfx as I have had issues in the past getting dual displays to work.

I'll keep working on it but so far this is the most compatible build I have had so thanks again.

**Comment by randyzhong** [comment]
No new updates, hence closing this issue.
