### ISSUE TITLE
升级到big sur后wifi无法驱动

### ISSUE THREAD

**Issue by PilotSnail** [randyzhong/HP-EliteDesk-800-G2-DM-Hackintosh#2]
使用opencore引导，白苹果博通BCM943224PCIEBT2 300Mbps 2.4&5G WiFi bluetooth 4.0的蓝牙正常，但wifi无法使用，AirportBrcmFixup.kext补丁倒入，通过添加此网卡参数PciRoot(0x0)/Pci(0x1C,0x0)/Pci(0x0,0x0)
pci14e4,4353仍无法驱动，求解，谢谢！

**Comment by randyzhong** [comment]
你可以看下第一个问题 #1 
可以修改 USBPorts.kext，把 USR01 替换为 HS07 试试看。

**Comment by PilotSnail** [comment]
ok，我回头试试看，谢谢
