### ISSUE TITLE
Audio and sleep issues

### ISSUE THREAD

**Issue by jaysonhubt** [randyzhong/HP-EliteDesk-800-G2-DM-Hackintosh#3]
Hi @randyzhong,
I created my EFI follow Opencore guide and I meet audio and sleep issues too.
I tried to fix it follow post-install guide but i can't resolved. (Change layoutid to 11/15/88)
I'm not sure I did right way.
Do you try to fix it by this way?
So inconvenient when use hackintosh without audio :'(

Thank for reading!

**Comment by randyzhong** [comment]
@jaysonhubt 
**Sleep:** So far there is no solution to resolve sleep issue as I know. So I disabled sleep mode.
**Audio:** Front Combo jack is not working, I didn't see a layout-id fixing it. But internal speaker and headphone output should be good. If your audio issue is not coming from the combo jack, then please post your hardware specs and OpenCore config.plist for further troubleshooting.

**Comment by jaysonhubt** [comment]
@randyzhong Both internal speaker and headphone output of my HP doesn't work. This is my EFI: https://github.com/jaysonhubt/Hackintosh-HP-800-G2-DM, please help me check.
Thank for your support!

**Comment by randyzhong** [comment]
Seems you are not follow my EFI.
You might have wrong configurations in <key>DeviceProperties</key>, that's why you don't get Audio working.
And you are not customized your USB ports.

**Comment by jaysonhubt** [comment]
I want create my own EFI so I follow OPC guide, maybe I missed somethings. Thank for your support! I'll try your EFI.
