### ISSUE TITLE
bcm943224pciebt2 拆机卡WiFi在升级11.3后无法工作

### ISSUE THREAD

**Issue by PilotSnail** [randyzhong/HP-EliteDesk-800-G2-DM-Hackintosh#4]
如题，使用您的WiFi文件，蓝牙可以工作，但是WiFi无法工作。请问我该如何操作呢？

**Comment by randyzhong** [comment]
抱歉，本人的机器没有无线/蓝牙设备，所以无法验证。
您的意思是升级之前是可以正常工作的？那升级之前的系统版本是多少？

**Comment by PilotSnail** [comment]
升级之前是11.2.3，前面两次的小升级都没有问题。这次升级到11.3原来的opencore0.66版本EFI出现了USB口只认前面板最右一个的情况，WIFI可用。更换成0.68的EFI后USB口正常，蓝牙正常，但WIFI没了。应该是11.3有了新的安全机制吧。另外升级后桌面多出来一个什么配置文件夹。

**Comment by PilotSnail** [comment]
我已经自己弄好了，谢谢。请删除这个吧。
