### ISSUE TITLE
Dual monitor not working

### ISSUE THREAD

**Issue by loisdroug27** [randyzhong/HP-EliteDesk-800-G2-DM-Hackintosh#5]
Hi, i have the same configuration as you except for the processor (i5 6600) and i cant manage to get the secondary DP port working. Only the one at the edge of the computer work and if i plug another one i see the screen blinking but nothing else. Do you manage to get another display port working. I'm booting on catalina last update. Can you give me some advice please.
Thank you for your work.

**Comment by randyzhong** [comment]
1. Change BIOS `Advanced > Option ROM Launch Policy > Configure Option ROM Launch Policy` > **All UEI**
2. Add boot-args **agdpmod=pikera** or **agdpmod=vit9696** to disable AGDP as iMac17,1 doesn't support multiple displays
3. Remove all connector FB patches, ensure AAPL,ig-platform-id is set to 0x19120000 (00001219)
4. Clear NVRAM and reboot

I tried two 2K monitors: Dell P2418D, it works fine on Big Sur 11.3.1. Might also work for Catalina.
Good luck!
