### ISSUE TITLE
Ended up with a black screen

### ISSUE THREAD

**Issue by lenylopez19** [randyzhong/HP-EliteDesk-800-G2-DM-Hackintosh#6]
Hi mate , i have the same pc as you, but the 35w version (i5 6500t) I tried all your files without any modification and I couldn't get to the installer.

so I tried the guide from open cores website using your kext files and copying the values from your .plist to the new one, and the installation booted up just fine but I didn't have network for downloading the installer.

 Tried both Intel kext for networking and nothing. So I decided to try the "offline" method and it went smoothly all the process without an error, rebooted several times all working, when the installer finished and the PC rebooted , rigth after the verbose boot screen I got a black screen and the says there's no video signal, the keyboard responds and all but no image. Any help ?

**Comment by randyzhong** [comment]
I would suggest you using the offline mode which requires a macOS offline USB.
Can you try my today's updated EFI? I made some changes on the graphics settings.

**Comment by TCB13** [comment]
Hello,

I'm also using an i5 machine and got the same result. Installation went smoothly and after the last reboot this is what happened:

1. The machine complained about an invalid system RTC time and said it reset the time to defaults;
2. HP recovery was launched (that black diagnostic screen that it totally useless) selected exit;
3. Machine rebooted once again and I got a black screen.

HP EliteDesk 800 G2 DM 65W
Processor: Intel(R) Core(TM) i5-6500 CPU @3.20GHZ
Memory Size: 8192 MB
**System BIOS: N21 Ver. 02.53 04/16/2021**

With the EFI folder copied from the repository I can't make Catalina to install at all and Big Sur usually only boots once (stuck on the middle of the apple logo progress bar). Doing a system restore makes it boot again.

I used both offline (macOS 11.6 downloaded in a real mac) and net recovery installer (macOS 11.2.1 (20D75) Recovery Image that eventually downloaded 11.6 from Apple).

 Also did this to have secure boot: https://github.com/randyzhong/HP-EliteDesk-800-G2-DM-Hackintosh/issues/9#issuecomment-1146641606

________________________________________________

Decided to give a try to Catalina, first install step went fine but after the first reboot the picker didn't show the internal hard drive. EFI Shell didn't show the drive as well.

Tried this fix https://www.reddit.com/r/hackintosh/comments/praqnu/comment/hdhckcj/?utm_source=share&utm_medium=web2x&context=3 and got a new error:  
````
OCB: LoadImage failed - Unsupported
````

Disabling secure boot makes to the Apple logo and then I get a forbidden symbol...

________________________________________________

After spending a weekend trying to make this EFI work, I decided to give a try to the latest macOS with this one https://github.com/frostyviking/HP-EliteDesk-800-G2-OC and it all worked fine :)

**My BIOS is also from 2021 and the one in this repository is from 2016, I'm not sure if that has anything to do with my issues but frostyviking's EFI worked fine at the first try**. I was even able to copy it to the internal partition and have it boot without issues.

I would really like to run Catalina but it seems I wont' be able to.

Thank you all.
