### ISSUE TITLE
OpenCore Bootup with no install option 

### ISSUE THREAD

**Issue by dereek5755** [randyzhong/HP-EliteDesk-800-G2-DM-Hackintosh#7]
hi,  i try to install the Mac Big Sur OS , i used your EFI (HP-EliteDesk-800-G2-DM-Hackintosh-main) with only edit the config file to add the SMBIOS info. but the boot-up does not show any option to install. only have UEFI shell, shoutdown, clear NVRM, Reset NVRM option. 
![IMG_5286](https://user-images.githubusercontent.com/89029673/129589832-1b4cbfab-11fa-4845-bf96-1d4dca1af8d2.JPG)

the BIOS configure are follows the request as well. any idea where is the part I miss out ?

**Comment by randyzhong** [comment]
This EFI doesn't support install macOS online. You should create a bootable USB Big Sur installer.

**Comment by ruibinjiang** [comment]
This is not an issue with online vs offline install. Can confirm the same issue exists when trying to install Big Sur 11.6 with an offline installer.

**Comment by randyzhong** [comment]
What's your HDD device? Is it a NVMe SSD?

**Comment by dereek5755** [comment]
Hi，I’m use Kingston 480GB  SSD HDD.

**Comment by ruibinjiang** [comment]
> What's your HDD device? Is it a NVMe SSD?

I don't think that's the issue here. The installation partition is on the flash drive. Regardless, I'm only using a SATA SSD.

I'm not sure why you say the script "only allows offline installer" since that's not a limitation of OpenCore. 

I had to use an alternative repo and install Catalina instead.

**Comment by randyzhong** [comment]
Oh sorry, I was thinking you can't find the hard disk, but it's about the USB installer, my bad.

I missed two options of **ScanPolicy** in config.plist
- OC_SCAN_ALLOW_FS_HFS
- OC_SCAN_ALLOW_DEVICE_USB

Will fix in my next release. Thanks.

**Comment by ruibinjiang** [comment]
> Oh sorry, I was thinking you can't find the hard disk, but it's about the USB installer, my bad.
> 
> I missed two options of **ScanPolicy** in config.plist
> 
> * OC_SCAN_ALLOW_FS_HFS
> * OC_SCAN_ALLOW_DEVICE_USB
> 
> Will fix in my next release. Thanks.

Ah right. That sure would cause the issue. I totally forgot to check that lol.

**Comment by dereek5755** [comment]
Hi Randy.

Thanks. I will try and share the status with you again
